from typing import Dict, List, TypedDict

from app.schemas.quote import QuoteCategory


class CategoryInfo(TypedDict):
    description: str
    subtopics: List[str]
    style: str
    tavily_query: str


CATEGORY_INFOS: Dict[QuoteCategory, CategoryInfo] = {
    QuoteCategory.CORE_PERSONAL_GROWTH: {
        "description": "Short insights focused on daily improvement.",
        "subtopics": [
            "Discipline",
            "Focus",
            "Clarity",
            "Growth Mindset",
            "Confidence",
            "Resilience",
            "Habits",
            "Self-Esteem",
            "Inner Strength",
            "Motivation",
        ],
        "style": "Motivating, actionable, clear, direct.",
        "tavily_query": "Best quotes and insights about personal growth discipline focus confidence resilience",
    },
    QuoteCategory.PSYCHOLOGY: {
        "description": "Daily micro-insights based on cognitive and emotional patterns.",
        "subtopics": [
            "Cognitive Biases",
            "Emotional Intelligence",
            "Attachment Styles",
            "Shadow Work (Jung)",
            "Self-Awareness",
            "Boundaries",
            "Overthinking",
            "Anxiety Relief",
            "Behavioral Patterns",
            "Social Dynamics",
        ],
        "style": "Insightful, reflective, analytical, empathetic.",
        "tavily_query": "Psychology facts and insights about cognitive biases emotional intelligence attachment styles shadow work",
    },
    QuoteCategory.PHILOSOPHY: {
        "description": "Short wisdom based on timeless ideas.",
        "subtopics": [
            "Stoicism",
            "Existentialism",
            "Taoism",
            "Minimalism Philosophy",
            "Modern Philosophy",
            "Spiritual Calm",
            "Ancient Wisdom",
            "Marcus Aurelius",
            "Seneca",
            "Alan Watts-inspired",
        ],
        "style": "Profound, timeless, stoic, contemplative.",
        "tavily_query": "Deep philosophical quotes and wisdom stoicism existentialism taoism marcus aurelius seneca",
    },
    QuoteCategory.MENTAL_HEALTH_WELLNESS: {
        "description": "Soft, calming micro-insights.",
        "subtopics": [
            "Calm & Stillness",
            "Healing",
            "Self-Compassion",
            "Letting Go",
            "Breathing & Grounding",
            "Mindfulness",
            "Acceptance",
            "Gratitude",
            "Emotional Release",
            "Loneliness Support",
        ],
        "style": "Gentle, soothing, compassionate, calming.",
        "tavily_query": "Comforting quotes and insights for mental health healing mindfulness self-compassion anxiety relief",
    },
    QuoteCategory.FITNESS_BODY: {
        "description": "Clear, sharp, actionable insights.",
        "subtopics": [
            "Discipline Training",
            "Gym Motivation",
            "Fat Loss Insight",
            "Longevity",
            "Sleep Optimization",
            "Recovery",
            "Hormones & Energy",
            "Metabolic Health",
            "Strength Building",
            "Performance Mindset",
        ],
        "style": "Energetic, disciplined, direct, no-nonsense.",
        "tavily_query": "Best fitness advice and motivation quotes strength training longevity biohacking sleep optimization",
    },
    QuoteCategory.WORK_PRODUCTIVITY_MONEY: {
        "description": "High-value fast insights.",
        "subtopics": [
            "Productivity",
            "Deep Work",
            "Time Management",
            "Creativity Sparks",
            "Entrepreneurship",
            "Career Insight",
            "Leadership",
            "Money Psychology",
            "Wealth & Investing",
            "Business Thinking",
        ],
        "style": "Professional, strategic, efficient, empowering.",
        "tavily_query": "Productivity hacks and business insights deep work entrepreneurship leadership wealth mindset",
    },
    QuoteCategory.LIFE_RELATIONSHIPS: {
        "description": "Human behavior + connection.",
        "subtopics": [
            "Relationships",
            "Masculinity",
            "Femininity",
            "Dating Psychology",
            "Red Flags",
            "Friendship Insight",
            "Human Nature",
            "Communication",
            "Family Dynamics",
            "Modern Love",
        ],
        "style": "Empathetic, observant, deep, relatable.",
        "tavily_query": "Psychology of relationships dating advice modern love communication skills friendship insights",
    },
    QuoteCategory.TECH_AI_FUTURE: {
        "description": "Future-oriented insight categories.",
        "subtopics": [
            "AI Daily Insight",
            "Future Thinking",
            "Tech Mindset",
            "Robotics & Automation",
            "Space & Exploration",
            "Cyber Psychology",
            "Human + AI Coexistence",
            "Innovation Spark",
            "Visionary Insight",
        ],
        "style": "Visionary, modern, analytical, forward-looking.",
        "tavily_query": "Latest developments and future predictions in AI robotics space exploration technology trends 2024 2025",
    },
    QuoteCategory.CREATIVE_ARTISTIC: {
        "description": "Designed for artistic minds.",
        "subtopics": [
            "Design Philosophy",
            "Creativity Boost",
            "Art & Expression",
            "Architectural Insight",
            "Storytelling",
            "Music & Mood",
            "Pattern Recognition",
            "Color & Emotion",
            "Imagination",
            "Creative Problem-Solving",
        ],
        "style": "Inspirational, abstract, expressive, imaginative.",
        "tavily_query": "Inspirational quotes for artists creativity design philosophy storytelling artistic expression",
    },
    QuoteCategory.TREND_ADAPTIVE: {
        "description": "These can follow the global news cycle.",
        "subtopics": [
            "Today's Big Idea",
            "Trending Mindset",
            "World Insight",
            "AI News Simplified",
            "Finance Snapshot",
            "Micro-Economics Insight",
            "Tech Trend of the Day",
            "Global Events Reflection",
            "Cultural Meaning of Today",
            "Fast Thought (Lightning Insight)",
        ],
        "style": "Relevant, timely, sharp, informative.",
        "tavily_query": "Global trending news cultural events and big ideas today current viral topics",
    },
    QuoteCategory.HISTORY: {
        "description": "Facts about History by country.",
        "subtopics": [
            "World History",
            "Ancient Civilizations",
            "Modern History",
            "Cultural Heritage",
            "Historical Figures",
            "War & Peace",
            "Strategy",
            "Civilization",
            "Human Nature",
            "Country Facts",
        ],
        "style": "Educational, narrative, factual, interesting.",
        "tavily_query": "Interesting historical facts and anecdotes ancient civilizations world history lessons war strategy",
    },
}
